version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: presupuesto-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
    ports:
      - "55432:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - presupuesto-net

volumes:
  mysql_data:

networks:
  presupuesto-net:
